apiVersion: apps/v1
kind: Deployment
metadata:
  name: dff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dff
  template:
    metadata:
      labels:
        app: dff
    spec:
      containers:
      - image: okteto.dev/dff:latest
        name: dff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "909193df-2d1f-4d1e-a4ab-f615d85ceaee"
        - name: Vless_Path
          value: "/vlggr"
        - name: Vmess_UUID
          value: "909193df-2d1f-4d1e-a4ab-f615d85ceaee"
        - name: Vmess_Path
          value: "/vm6dd"
        - name: Share_Path
          value: "/v2link"
