apiVersion: apps/v1
kind: Deployment
metadata:
  name: xdh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xdh
  template:
    metadata:
      labels:
        app: xdh
    spec:
      containers:
      - image: okteto.dev/xdh:latest
        name: xdh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "uu:34452768-ecbd-4d1d-8b46-458fb7d6058f"
        - name: Vless_Path
          value: "/vlddc"
        - name: Vmess_UUID
          value: "uu:34452768-ecbd-4d1d-8b46-458fb7d6058f"
        - name: Vmess_Path
          value: "/vmaaa"
        - name: Share_Path
          value: "/v2link"
